# This file was generated by GoReleaser. DO NOT EDIT.
cask "klarion" do
  version "0.4.3"

  on_macos do
    on_arm do
      sha256 "767982a9aeb38390ce9f8796eb2aa0d2171238fece2323277fc944db07fb4137"
      url "https://github.com/0x1Adi/Klarion/releases/download/v#{version}/klarion_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c15f567973404585b2bda468700d8e6690023ff290fdc7c3150e430311bdcd82"
      url "https://github.com/0x1Adi/Klarion/releases/download/v#{version}/klarion_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3bf7f767b43a8ae63290b9fd90a23908656f3dcc8436e0baffd1fd428cba1a4"
      url "https://github.com/0x1Adi/Klarion/releases/download/v#{version}/klarion_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "2913467788c020094a3b7491a67e87e972b6a36eece0cbacaa9a87a98d622755"
      url "https://github.com/0x1Adi/Klarion/releases/download/v#{version}/klarion_#{version}_linux_amd64.tar.gz"
    end
  end

  name "klarion"
  desc "Secret scanning that a model verifies. Entropy narrows the search, an LLM decides what is real."
  homepage "https://github.com/0x1Adi/Klarion"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "klarion"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/klarion"]
    end
  end

  # No zap stanza required
end
